name: gotrue_wechatlogin
description: A dart client library for the GoTrue API.
version: 2.7.3
homepage: 'https://memfiredb.com/'
repository: 'https://github.com/LucaRao/gotrue_wechat'
documentation: 'https://docs.memfiredb.com/docs/app/sdkdocs/dart/auth/auth-signup/'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.2
  http: '>=0.13.0 <2.0.0'
  jwt_decode: ^0.3.1
  retry: ^3.1.0
  rxdart: ^0.27.7
  meta: ^1.7.0

dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^4.1.0
  lints: ^2.1.1
  test: ^1.16.4
  otp: ^3.1.3

false_secrets:
- /infra/gotrue/docker-compose.yml
